name: Sync Repo Code
 
on:
  webhook:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: 'your-branch-name'
 
    - name: Setup Git
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
    - name: Sync Code
      uses: easingthemes/action-git-sync@master
      with:
        source_repo: 'git@github.com:ansoncloud8/am-cf-linklet.git'
        source_branch: 'main'
        target_branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
