name: Sync Fork
 
on:
  push:
    branches: [ main ]
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: main
 
      - name: Sync with Upstream
        uses: cpina/github-actions-sync-fork@master
        with:
          UPSTREAM_USER: 'ansoncloud8'
          UPSTREAM_REPO: 'am-cf-linklet'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
